export type BpscMathPart =
  | { kind: "text"; value: string }
  | { kind: "math"; value: string };

const exactMathExpressions: Record<string, string> = {
  "(ε₀A/t)(k₁ + k₂)": String.raw`\frac{\varepsilon_0 A}{t}(k_1+k_2)`,
  "(ε₀A/t) · ((k₁ + k₂)/2)": String.raw`\frac{\varepsilon_0 A}{t}\cdot\frac{k_1+k_2}{2}`,
  "(2ε₀A/t)(k₁ + k₂)": String.raw`\frac{2\varepsilon_0 A}{t}(k_1+k_2)`,
  "(ε₀A/t) · ((k₁ - k₂)/2)": String.raw`\frac{\varepsilon_0 A}{t}\cdot\frac{k_1-k_2}{2}`,
  "6F": String.raw`6\,\mathrm{F}`,
  "3/2 F": String.raw`\frac{3}{2}\,\mathrm{F}`,
  "2/3 F": String.raw`\frac{2}{3}\,\mathrm{F}`,
  "5F": String.raw`5\,\mathrm{F}`,
  "3K/(K + 4)": String.raw`\frac{3K}{K+4}`,
  "3K/4": String.raw`\frac{3K}{4}`,
  "4K/(K + 3)": String.raw`\frac{4K}{K+3}`,
  "4K/3": String.raw`\frac{4K}{3}`,
  "1": String.raw`1`,
  "Q(R² + r²)/[4πε₀(R + r)]": String.raw`\frac{Q(R^2+r^2)}{4\pi\varepsilon_0(R+r)}`,
  "QR/(R + r)": String.raw`\frac{QR}{R+r}`,
  "Q(R + r)/[4πε₀(R² + r²)]": String.raw`\frac{Q(R+r)}{4\pi\varepsilon_0(R^2+r^2)}`,
  "V = p cos θ/(4πε₀r²)": String.raw`V=\frac{p\cos\theta}{4\pi\varepsilon_0r^2}`,
  "V = p cos θ/(4πε₀r)": String.raw`V=\frac{p\cos\theta}{4\pi\varepsilon_0r}`,
  "V = p sin θ/(4πε₀r)": String.raw`V=\frac{p\sin\theta}{4\pi\varepsilon_0r}`,
  "V = p cos θ/(2πε₀r²)": String.raw`V=\frac{p\cos\theta}{2\pi\varepsilon_0r^2}`,
  "(4/3) sin i": String.raw`\frac{4}{3}\sin i`,
  "1/sin i": String.raw`\frac{1}{\sin i}`,
  "4/3": String.raw`\frac{4}{3}`,
  "90°": String.raw`90^\circ`,
  "180°": String.raw`180^\circ`,
  "120°": String.raw`120^\circ`,
  "45°": String.raw`45^\circ`,
  "15 cm": String.raw`15\,\mathrm{cm}`,
  "12.5 cm": String.raw`12.5\,\mathrm{cm}`,
  "7.5 cm": String.raw`7.5\,\mathrm{cm}`,
  "10 cm": String.raw`10\,\mathrm{cm}`,
  "10 : 8": String.raw`10:8`,
  "9 : 1": String.raw`9:1`,
  "4 : 1": String.raw`4:1`,
  "2 : 1": String.raw`2:1`,
  "1 : 1": String.raw`1:1`,
  "1 : 4": String.raw`1:4`,
  "λd/D": String.raw`\frac{\lambda d}{D}`,
  "λD/d": String.raw`\frac{\lambda D}{d}`,
  "dD/λ": String.raw`\frac{dD}{\lambda}`,
  "λd/(4D)": String.raw`\frac{\lambda d}{4D}`,
  "sin⁻¹(n)": String.raw`\sin^{-1}(n)`,
  "sin⁻¹(1/n)": String.raw`\sin^{-1}\!\left(\frac{1}{n}\right)`,
  "tan⁻¹(1/n)": String.raw`\tan^{-1}\!\left(\frac{1}{n}\right)`,
  "tan⁻¹(n)": String.raw`\tan^{-1}(n)`,
  "1/4": String.raw`\frac{1}{4}`,
  "1/2": String.raw`\frac{1}{2}`,
  "1/8": String.raw`\frac{1}{8}`,
  "1/16": String.raw`\frac{1}{16}`,
  "20 mA": String.raw`20\,\mathrm{mA}`,
  "5 mA": String.raw`5\,\mathrm{mA}`,
  "10 mA": String.raw`10\,\mathrm{mA}`,
  "15 mA": String.raw`15\,\mathrm{mA}`,
  "0.75 A": String.raw`0.75\,\mathrm{A}`,
  "0.25 A": String.raw`0.25\,\mathrm{A}`,
  "0.5 A": String.raw`0.5\,\mathrm{A}`,
  "A = 0, B = 1, C = 0": String.raw`A=0,\ B=1,\ C=0`,
  "A = 1, B = 0, C = 0": String.raw`A=1,\ B=0,\ C=0`,
  "A = 1, B = 0, C = 1": String.raw`A=1,\ B=0,\ C=1`,
  "A = 1, B = 1, C = 0": String.raw`A=1,\ B=1,\ C=0`,
  "2.2 m/s": String.raw`2.2\,\mathrm{m\,s^{-1}}`,
  "1.8 m/s": String.raw`1.8\,\mathrm{m\,s^{-1}}`,
  "1.4 m/s": String.raw`1.4\,\mathrm{m\,s^{-1}}`,
  "0.6 m/s": String.raw`0.6\,\mathrm{m\,s^{-1}}`,
  "mgH": String.raw`mgH`,
  "√(2gH)": String.raw`\sqrt{2gH}`,
  "2gH": String.raw`2gH`,
  "T₁ > T₂ > T₃": String.raw`T_1>T_2>T_3`,
  "T₁ > T₃ > T₂": String.raw`T_1>T_3>T_2`,
  "T₂ > T₃ > T₁": String.raw`T_2>T_3>T_1`,
  "T₃ > T₂ > T₁": String.raw`T_3>T_2>T_1`,
  "P₀V₀": String.raw`P_0V_0`,
  "2P₀V₀": String.raw`2P_0V_0`,
  "P₀V₀/2": String.raw`\frac{P_0V_0}{2}`,
  "PV": String.raw`PV`,
  "2PV": String.raw`2PV`,
  "4PV": String.raw`4PV`,
  "p₀v₀": String.raw`p_0v_0`,
  "(13/2)p₀v₀": String.raw`\frac{13}{2}p_0v_0`,
  "(11/2)p₀v₀": String.raw`\frac{11}{2}p_0v_0`,
  "4p₀v₀": String.raw`4p_0v_0`,
  "K₁/2 + K₂": String.raw`\frac{K_1}{2}+K_2`,
  "[1/(2K₁) + 1/K₂]⁻¹": String.raw`\left[\frac{1}{2K_1}+\frac{1}{K_2}\right]^{-1}`,
  "1/(2K₁) + 1/K₂": String.raw`\frac{1}{2K_1}+\frac{1}{K_2}`,
  "[2/K₁ + 1/K₁]⁻¹": String.raw`\left[\frac{2}{K_1}+\frac{1}{K_1}\right]^{-1}`,
  "K₁ + K₂": String.raw`K_1+K_2`,
  "K₁K₂/(K₁ + K₂)": String.raw`\frac{K_1K_2}{K_1+K_2}`,
  "K₁ - K₂": String.raw`K_1-K_2`,
  "K₁K₂/(K₁ - K₂)": String.raw`\frac{K_1K_2}{K_1-K_2}`,
  "3.0 m/s": String.raw`3.0\,\mathrm{m\,s^{-1}}`,
  "1.5 m/s": String.raw`1.5\,\mathrm{m\,s^{-1}}`,
  "1.0 m/s": String.raw`1.0\,\mathrm{m\,s^{-1}}`,
  "2.25 m/s": String.raw`2.25\,\mathrm{m\,s^{-1}}`,
  "g₁/g₂ = R₁/R₂": String.raw`\frac{g_1}{g_2}=\frac{R_1}{R_2}`,
  "g₁/g₂ = R₂/R₁": String.raw`\frac{g_1}{g_2}=\frac{R_2}{R_1}`,
  "g₁/g₂ = R₁²/R₂²": String.raw`\frac{g_1}{g_2}=\frac{R_1^2}{R_2^2}`,
  "g₁/g₂ = R₁³/R₂³": String.raw`\frac{g_1}{g_2}=\frac{R_1^3}{R_2^3}`,
  "g/2": String.raw`\frac{g}{2}`,
  "g/3": String.raw`\frac{g}{3}`,
  "g/9": String.raw`\frac{g}{9}`,
  "g": String.raw`g`,
  "1/√2 s": String.raw`\frac{1}{\sqrt{2}}\,\mathrm{s}`,
  "2√2 s": String.raw`2\sqrt{2}\,\mathrm{s}`,
  "2 s": String.raw`2\,\mathrm{s}`,
  "1/2 s": String.raw`\frac{1}{2}\,\mathrm{s}`,
  "5R": String.raw`5R`,
  "15R": String.raw`15R`,
  "3R": String.raw`3R`,
  "4R": String.raw`4R`,
  "4GMₚ/Dₚ²": String.raw`\frac{4GM_p}{D_p^2}`,
  "GMₚm/Dₚ²": String.raw`\frac{GM_pm}{D_p^2}`,
  "GMₚ/Dₚ²": String.raw`\frac{GM_p}{D_p^2}`,
  "4GMₚm/Dₚ²": String.raw`\frac{4GM_pm}{D_p^2}`,
  "−24πε₀ar": String.raw`-24\pi a\varepsilon_0 r`,
  "−6aε₀r": String.raw`-6a\varepsilon_0 r`,
  "−24πε₀a": String.raw`-24\pi a\varepsilon_0`,
  "−6aε₀": String.raw`-6a\varepsilon_0`,
  "2q/ε₀": String.raw`\frac{2q}{\varepsilon_0}`,
  "q/(8ε₀)": String.raw`\frac{q}{8\varepsilon_0}`,
  "q/ε₀": String.raw`\frac{q}{\varepsilon_0}`,
  "Q/ε₀": String.raw`\frac{Q}{\varepsilon_0}`,
  "3q a²/(2ε₀)": String.raw`\frac{3qa^2}{2\varepsilon_0}`,
  "ε₀A/(d₁/K₁ + d₂/K₂ + d₃/K₃)": String.raw`\frac{\varepsilon_0A}{\frac{d_1}{K_1}+\frac{d_2}{K_2}+\frac{d_3}{K_3}}`,
  "ε₀A/[(d₁ + d₂ + d₃)/(K₁ + K₂ + K₃)]": String.raw`\frac{\varepsilon_0A}{\frac{d_1+d_2+d_3}{K_1+K_2+K_3}}`,
  "ε₀A(K₁K₂K₃)/(d₁d₂d₃)": String.raw`\frac{\varepsilon_0A K_1K_2K_3}{d_1d_2d_3}`,
  "ε₀(AK₁/d₁ + AK₂/d₂ + AK₃/d₃)": String.raw`\varepsilon_0\left(\frac{AK_1}{d_1}+\frac{AK_2}{d_2}+\frac{AK_3}{d_3}\right)`,
  "√[(g+qE/m)/g]": String.raw`\sqrt{\frac{g+\frac{qE}{m}}{g}}`,
  "[g/(g+qE/m)]³ᐟ²": String.raw`\left(\frac{g}{g+\frac{qE}{m}}\right)^{3/2}`,
  "√[g/(g+qE/m)]": String.raw`\sqrt{\frac{g}{g+\frac{qE}{m}}}`,
  "VAB = VBC = 100 V": String.raw`V_{AB}=V_{BC}=100\,\mathrm{V}`,
  "VAB = 75 V, VBC = 25 V": String.raw`V_{AB}=75\,\mathrm{V},\quad V_{BC}=25\,\mathrm{V}`,
  "VAB = 25 V, VBC = 75 V": String.raw`V_{AB}=25\,\mathrm{V},\quad V_{BC}=75\,\mathrm{V}`,
  "VAB = VBC = 50 V": String.raw`V_{AB}=V_{BC}=50\,\mathrm{V}`,
  "5 amp": String.raw`5\,\mathrm{A}`,
  "3 amp": String.raw`3\,\mathrm{A}`,
  "−3 amp": String.raw`-3\,\mathrm{A}`,
  "−5/6 amp": String.raw`-\frac{5}{6}\,\mathrm{A}`,
  "5 Ω": String.raw`5\,\Omega`,
  "10 Ω": String.raw`10\,\Omega`,
  "15 Ω": String.raw`15\,\Omega`,
  "20 Ω": String.raw`20\,\Omega`,
  "8/3 A": String.raw`\frac{8}{3}\,\mathrm{A}`,
  "9/13 A": String.raw`\frac{9}{13}\,\mathrm{A}`,
  "4/13 A": String.raw`\frac{4}{13}\,\mathrm{A}`,
  "1/3 A": String.raw`\frac{1}{3}\,\mathrm{A}`,
  "2/3 A": String.raw`\frac{2}{3}\,\mathrm{A}`,
  "3 A": String.raw`3\,\mathrm{A}`,
  "9 A": String.raw`9\,\mathrm{A}`,
  "13 A": String.raw`13\,\mathrm{A}`,
  "19 A": String.raw`19\,\mathrm{A}`,
  "54/12 Ω": String.raw`\frac{54}{12}\,\Omega`,
  "20/11 Ω": String.raw`\frac{20}{11}\,\Omega`,
  "48/11 Ω": String.raw`\frac{48}{11}\,\Omega`,
  "11/48 Ω": String.raw`\frac{11}{48}\,\Omega`,
  "nG": String.raw`nG`,
  "(n−1)G": String.raw`(n-1)G`,
  "G/n": String.raw`\frac{G}{n}`,
  "G/(n−1)": String.raw`\frac{G}{n-1}`,
  "7μ₀I/(16R) ⊗": String.raw`\frac{7\mu_0I}{16R}\,\otimes`,
  "7μ₀I/(16R) ⊙": String.raw`\frac{7\mu_0I}{16R}\,\odot`,
  "5μ₀I/(16R) ⊗": String.raw`\frac{5\mu_0I}{16R}\,\otimes`,
  "5μ₀I/(16R) ⊙": String.raw`\frac{5\mu_0I}{16R}\,\odot`,
  "Rd = √2 Rp": String.raw`R_d=\sqrt{2}\,R_p`,
  "Rd = Rp/√2": String.raw`R_d=\frac{R_p}{\sqrt{2}}`,
  "Rd = Rp": String.raw`R_d=R_p`,
  "Rd = 2Rp": String.raw`R_d=2R_p`,
  "1.4×10⁻⁴ N towards right": String.raw`1.4\times10^{-4}\,\mathrm{N}\;\text{towards right}`,
  "1.4×10⁻⁴ N towards left": String.raw`1.4\times10^{-4}\,\mathrm{N}\;\text{towards left}`,
  "2.6×10⁻⁴ N to the right": String.raw`2.6\times10^{-4}\,\mathrm{N}\;\text{to the right}`,
  "2.6×10⁻⁴ N to the left": String.raw`2.6\times10^{-4}\,\mathrm{N}\;\text{to the left}`,
  "3.2 T year": String.raw`3.2T\,\mathrm{year}`,
  "4.6 T year": String.raw`4.6T\,\mathrm{year}`,
  "6.6 T year": String.raw`6.6T\,\mathrm{year}`,
  "9.2 T year": String.raw`9.2T\,\mathrm{year}`,
  "2:1": String.raw`2:1`,
  "1:2": String.raw`1:2`,
  "1:4": String.raw`1:4`,
  "1:16": String.raw`1:16`,
  "4:1": String.raw`4:1`,
  "½[IᵦIₜ/(Iₜ+Iᵦ)]ωᵢ²": String.raw`\frac{1}{2}\frac{I_bI_t}{I_t+I_b}\omega_i^2`,
  "½[Iᵦ²/(Iₜ+Iᵦ)]ωᵢ²": String.raw`\frac{1}{2}\frac{I_b^2}{I_t+I_b}\omega_i^2`,
  "½[Iₜ²/(Iₜ+Iᵦ)]ωᵢ²": String.raw`\frac{1}{2}\frac{I_t^2}{I_t+I_b}\omega_i^2`,
  "[(Iᵦ−Iₜ)/(Iₜ+Iᵦ)]ωᵢ²": String.raw`\frac{I_b-I_t}{I_t+I_b}\omega_i^2`,
  "v, v and v": String.raw`v,\ v\ \text{and}\ v`,
  "2v, √2v and zero": String.raw`2v,\ \sqrt{2}v\ \text{and zero}`,
  "2v, 2v and zero": String.raw`2v,\ 2v\ \text{and zero}`,
  "2v, √2v and √2v": String.raw`2v,\ \sqrt{2}v\ \text{and}\ \sqrt{2}v`,
  "2R/S": String.raw`\frac{2R}{S}`,
  "2S/R": String.raw`\frac{2S}{R}`,
  "2R²/S": String.raw`\frac{2R^2}{S}`,
  "2S/R²": String.raw`\frac{2S}{R^2}`,
  "3/8": String.raw`\frac{3}{8}`,
  "2/3": String.raw`\frac{2}{3}`,
  "3/4": String.raw`\frac{3}{4}`,
  "0.5": String.raw`0.5`,
  "urms > uav > ump": String.raw`u_{\mathrm{rms}}>u_{\mathrm{av}}>u_{\mathrm{mp}}`,
  "uav > urms > ump": String.raw`u_{\mathrm{av}}>u_{\mathrm{rms}}>u_{\mathrm{mp}}`,
  "ump > uav > urms": String.raw`u_{\mathrm{mp}}>u_{\mathrm{av}}>u_{\mathrm{rms}}`,
  "ump > urms > uav": String.raw`u_{\mathrm{mp}}>u_{\mathrm{rms}}>u_{\mathrm{av}}`,
};

const inlineMathExpressions = ([
  ["Q/ε₀", String.raw`\frac{Q}{\varepsilon_0}`],
  ["q/(8ε₀)", String.raw`\frac{q}{8\varepsilon_0}`],
  ["q/ε₀", String.raw`\frac{q}{\varepsilon_0}`],
  ["ρ = −ε₀∇²φ", String.raw`\rho=-\varepsilon_0\nabla^2\phi`],
  ["∇²(ar²) = 6a", String.raw`\nabla^2(ar^2)=6a`],
  ["ρ = −6aε₀", String.raw`\rho=-6a\varepsilon_0`],
  ["φ = ar² + b", String.raw`\phi=ar^2+b`],
  ["ε₀A/(d₁/K₁+d₂/K₂+d₃/K₃)", String.raw`\frac{\varepsilon_0A}{\frac{d_1}{K_1}+\frac{d_2}{K_2}+\frac{d_3}{K_3}}`],
  ["d₁/K₁+d₂/K₂+d₃/K₃", String.raw`\frac{d_1}{K_1}+\frac{d_2}{K_2}+\frac{d_3}{K_3}`],
  ["Σ(dᵢ/Kᵢ)", String.raw`\sum_i\frac{d_i}{K_i}`],
  ["d₁, d₂, d₃", String.raw`d_1,\ d_2,\ d_3`],
  ["K₁, K₂, K₃", String.raw`K_1,\ K_2,\ K_3`],
  ["E = σ/ε₀", String.raw`E=\frac{\sigma}{\varepsilon_0}`],
  ["T/T₀", String.raw`\frac{T}{T_0}`],
  ["g+qE/m", String.raw`g+\frac{qE}{m}`],
  ["T ∝ 1/√g_eff", String.raw`T\propto\frac{1}{\sqrt{g_{\mathrm{eff}}}}`],
  ["T₀", String.raw`T_0`],
  ["VAB = 4 V", String.raw`V_{AB}=4\,\mathrm{V}`],
  ["VAB", String.raw`V_{AB}`],
  ["VBC", String.raw`V_{BC}`],
  ["I₃", String.raw`I_3`],
  ["10+1+2 = 13 A", String.raw`10+1+2=13\,\mathrm{A}`],
  ["Ir", String.raw`Ir`],
  ["P = 3 Ω", String.raw`P=3\,\Omega`],
  ["l₁", String.raw`l_1`],
  ["P/Q = 55/45", String.raw`\frac{P}{Q}=\frac{55}{45}`],
  ["(P+x)/Q = 75/25", String.raw`\frac{P+x}{Q}=\frac{75}{25}`],
  ["x = 48/11 Ω", String.raw`x=\frac{48}{11}\,\Omega`],
  ["V/G", String.raw`\frac{V}{G}`],
  ["nV", String.raw`nV`],
  ["nG", String.raw`nG`],
  ["(n−1)G", String.raw`(n-1)G`],
  ["3π/2", String.raw`\frac{3\pi}{2}`],
  ["π/2", String.raw`\frac{\pi}{2}`],
  ["7μ₀I/(16R)", String.raw`\frac{7\mu_0I}{16R}`],
  ["r = √(2mK)/(qB) ∝ √m", String.raw`r=\frac{\sqrt{2mK}}{qB}\propto\sqrt{m}`],
  ["v = E/B", String.raw`v=\frac{E}{B}`],
  ["qE", String.raw`qE`],
  ["qvB", String.raw`qvB`],
  ["2.0×10⁻⁴ N", String.raw`2.0\times10^{-4}\,\mathrm{N}`],
  ["0.6×10⁻⁴ N", String.raw`0.6\times10^{-4}\,\mathrm{N}`],
  ["1.4×10⁻⁴ N", String.raw`1.4\times10^{-4}\,\mathrm{N}`],
  ["n(n−1)/2 = 4×3/2 = 6", String.raw`\frac{n(n-1)}{2}=\frac{4\times3}{2}=6`],
  ["(1/2)^(t/T) = 0.01", String.raw`\left(\frac{1}{2}\right)^{t/T}=0.01`],
  ["t/T = log₂100 ≈ 6.64", String.raw`\frac{t}{T}=\log_2 100\approx6.64`],
  ["₁₅P³² → ₁₆S³² + x + y", String.raw`{}_{15}^{32}\mathrm{P}\rightarrow{}_{16}^{32}\mathrm{S}+x+y`],
  ["β⁻", String.raw`\beta^-`],
  ["1/256", String.raw`\frac{1}{256}`],
  ["TX:TY", String.raw`T_X:T_Y`],
  ["TX = 1 h", String.raw`T_X=1\,\mathrm{h}`],
  ["TY = 2 h", String.raw`T_Y=2\,\mathrm{h}`],
  ["ωf = Iₜωᵢ/(Iₜ+Iᵦ)", String.raw`\omega_f=\frac{I_t\omega_i}{I_t+I_b}`],
  ["Iₜ", String.raw`I_t`],
  ["Iᵦ", String.raw`I_b`],
  ["ωᵢ", String.raw`\omega_i`],
  ["ωf", String.raw`\omega_f`],
  ["√2v", String.raw`\sqrt{2}v`],
  ["2S/R", String.raw`\frac{2S}{R}`],
  ["TA/TB = MA/MB", String.raw`\frac{T_A}{T_B}=\frac{M_A}{M_B}`],
  ["CA/CB", String.raw`\frac{C_A}{C_B}`],
  ["Crms ∝ √(T/M)", String.raw`C_{\mathrm{rms}}\propto\sqrt{\frac{T}{M}}`],
  ["TA/MA = TB/MB", String.raw`\frac{T_A}{M_A}=\frac{T_B}{M_B}`],
  ["urms = √(3RT/M)", String.raw`u_{\mathrm{rms}}=\sqrt{\frac{3RT}{M}}`],
  ["uav = √(8RT/πM)", String.raw`u_{\mathrm{av}}=\sqrt{\frac{8RT}{\pi M}}`],
  ["ump = √(2RT/M)", String.raw`u_{\mathrm{mp}}=\sqrt{\frac{2RT}{M}}`],
  ["urms", String.raw`u_{\mathrm{rms}}`],
  ["uav", String.raw`u_{\mathrm{av}}`],
  ["ump", String.raw`u_{\mathrm{mp}}`],
  ["200 Vm⁻¹", String.raw`200\,\mathrm{V\,m^{-1}}`],
  ["100 Vm⁻¹", String.raw`100\,\mathrm{V\,m^{-1}}`],
  ["50 Vm⁻¹", String.raw`50\,\mathrm{V\,m^{-1}}`],
  ["200 V m⁻¹", String.raw`200\,\mathrm{V\,m^{-1}}`],
  ["100 V m⁻¹", String.raw`100\,\mathrm{V\,m^{-1}}`],
  ["50 V m⁻¹", String.raw`50\,\mathrm{V\,m^{-1}}`],
  ["g = 9.8 m/s²", String.raw`g=9.8\,\mathrm{m\,s^{-2}}`],
  ["μw = 4/3", String.raw`\mu_w=\frac{4}{3}`],
  ["i = 45°", String.raw`i=45^\circ`],
  ["p = 2qa", String.raw`p=2qa`],
  ["r >> 2a", String.raw`r\gg 2a`],
  ["R (> r)", String.raw`R\;(>r)`],
  ["(3/4)d", String.raw`\frac{3}{4}d`],
  ["A metre²", String.raw`A\,\mathrm{m^2}`],
  ["A मीटर²", String.raw`A\,\mathrm{m^2}`],
  ["t metre", String.raw`t\,\mathrm{m}`],
  ["t मीटर", String.raw`t\,\mathrm{m}`],
  ["0.05 m", String.raw`0.05\,\mathrm{m}`],
  ["0.1 m", String.raw`0.1\,\mathrm{m}`],
  ["15 V", String.raw`15\,\mathrm{V}`],
  ["180°", String.raw`180^\circ`],
  ["120°", String.raw`120^\circ`],
  ["90°", String.raw`90^\circ`],
  ["45°", String.raw`45^\circ`],
  ["10cm", String.raw`10\,\mathrm{cm}`],
  ["10 cm", String.raw`10\,\mathrm{cm}`],
  ["5 cm", String.raw`5\,\mathrm{cm}`],
  ["2 F", String.raw`2\,\mathrm{F}`],
  ["2F", String.raw`2\,\mathrm{F}`],
  ["T₁, T₂ and T₃", String.raw`T_1,\ T_2\text{ and }T_3`],
  ["T₁, T₂ और T₃", String.raw`T_1,\ T_2,\ T_3`],
  ["Kₐ > Kᵦ", String.raw`K_A>K_B`],
  ["R₁ and R₂", String.raw`R_1\text{ and }R_2`],
  ["R₁ और R₂", String.raw`R_1,\ R_2`],
  ["g₁ and g₂", String.raw`g_1\text{ and }g_2`],
  ["g₁ और g₂", String.raw`g_1,\ g_2`],
  ["Mₚ", String.raw`M_p`],
  ["Dₚ", String.raw`D_p`],
  ["C₀", String.raw`C_0`],
  ["P₀", String.raw`P_0`],
  ["V₀", String.raw`V_0`],
  ["k₁", String.raw`k_1`],
  ["k₂", String.raw`k_2`],
  ["K₁", String.raw`K_1`],
  ["K₂", String.raw`K_2`],
  ["Kₐ", String.raw`K_A`],
  ["Kᵦ", String.raw`K_B`],
  ["S₁", String.raw`S_1`],
  ["S₂", String.raw`S_2`],
  ["R₁", String.raw`R_1`],
  ["R₂", String.raw`R_2`],
  ["g₁", String.raw`g_1`],
  ["g₂", String.raw`g_2`],
  ["μg", String.raw`\mu_g`],
  ["μw", String.raw`\mu_w`],
  ["ε₀", String.raw`\varepsilon_0`],
  ["θ", String.raw`\theta`],
  ["α", String.raw`\alpha`],
  ["β", String.raw`\beta`],
  ["γ", String.raw`\gamma`],
  ["1/16", String.raw`\frac{1}{16}`],
  ["9 : 1", String.raw`9:1`],
  ["1 : 2", String.raw`1:2`],
  ["2 : 1", String.raw`2:1`],
  ["P-V", String.raw`P\!-\!V`],
  ["p-v", String.raw`p\!-\!v`],
  ["ABCDA", String.raw`ABCDA`],
  ["AB", String.raw`AB`],
  ["BC", String.raw`BC`],
  ["CD", String.raw`CD`],
  ["DA", String.raw`DA`],
] satisfies Array<[string, string]>).sort((left, right) => right[0].length - left[0].length);

export function splitBpscMathText(value: string): BpscMathPart[] {
  const exact = exactMathExpressions[value];
  if (exact) return [{ kind: "math", value: exact }];

  const parts: BpscMathPart[] = [];
  let cursor = 0;

  while (cursor < value.length) {
    let nextIndex = value.length;
    let nextRule: [string, string] | undefined;

    for (const rule of inlineMathExpressions) {
      const index = value.indexOf(rule[0], cursor);
      if (index !== -1 && (index < nextIndex || (index === nextIndex && (!nextRule || rule[0].length > nextRule[0].length)))) {
        nextIndex = index;
        nextRule = rule;
      }
    }

    if (!nextRule) {
      parts.push({ kind: "text", value: value.slice(cursor) });
      break;
    }

    if (nextIndex > cursor) {
      parts.push({ kind: "text", value: value.slice(cursor, nextIndex) });
    }

    parts.push({ kind: "math", value: nextRule[1] });
    cursor = nextIndex + nextRule[0].length;
  }

  return parts;
}
