import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, "content", "tests", "class-12-board-2027-electrostatics.json");
const outputPath = path.join(root, "content", "tests", "class-12-board-2027-electrostatics-sets.json");

const pair = (en, hi = en) => ({ en, hi });
const q = (category, questionEn, questionHi, options, correctOption, explanationEn, explanationHi) => ({
  category,
  questionEn,
  questionHi,
  options: options.map((option) => Array.isArray(option) ? pair(option[0], option[1]) : pair(option)),
  correctOption,
  explanationEn,
  explanationHi,
});

const set2Questions = [
  q("Theory", "Which law ensures that the total charge of an isolated system remains constant?", "कौन-सा नियम सुनिश्चित करता है कि एक विलगित निकाय का कुल आवेश नियत रहता है?", [["Conservation of charge", "आवेश संरक्षण"], ["Gauss's law", "गाउस का नियम"], ["Ohm's law", "ओम का नियम"], ["Faraday's law", "फैराडे का नियम"]], 0, "Electric charge can transfer between bodies, but the total charge of an isolated system is conserved.", "विद्युत आवेश वस्तुओं के बीच स्थानांतरित हो सकता है, परंतु विलगित निकाय का कुल आवेश संरक्षित रहता है।"),
  q("Theory", "Charging a neutral conductor without touching it is called:", "किसी उदासीन चालक को बिना स्पर्श किए आवेशित करने की प्रक्रिया कहलाती है:", [["Conduction", "चालन"], ["Induction", "प्रेरण"], ["Polarisation only", "केवल ध्रुवण"], ["Earthing only", "केवल भू-संपर्क"]], 1, "Electrostatic induction separates and transfers charge without direct contact with the charged body.", "विद्युत स्थैतिक प्रेरण में आवेशित वस्तु से सीधे स्पर्श के बिना आवेशों का पृथक्करण और स्थानांतरण होता है।"),
  q("Fact", "Why can two electric field lines never intersect?", "दो विद्युत क्षेत्र रेखाएँ कभी एक-दूसरे को क्यों नहीं काट सकतीं?", [["The field would have two directions at one point", "एक बिंदु पर क्षेत्र की दो दिशाएँ हो जाएँगी"], ["The field would become zero everywhere", "क्षेत्र हर जगह शून्य हो जाएगा"], ["Charge would not be conserved", "आवेश संरक्षित नहीं रहेगा"], ["Potential would become infinite", "विभव अनंत हो जाएगा"]], 0, "The tangent to a field line gives the unique field direction. Intersection would imply two directions at one point.", "क्षेत्र रेखा की स्पर्शरेखा क्षेत्र की एक निश्चित दिशा बताती है। प्रतिच्छेदन से एक ही बिंदु पर दो दिशाएँ मिलेंगी।"),
  q("Theory", "In electrostatic equilibrium, excess charge given to a conductor resides:", "विद्युत स्थैतिक संतुलन में चालक को दिया गया अतिरिक्त आवेश कहाँ रहता है?", [["Only at its centre", "केवल केंद्र पर"], ["Throughout its volume uniformly", "पूरे आयतन में समान रूप से"], ["On its outer surface", "उसकी बाहरी सतह पर"], ["Only at the lowest point", "केवल सबसे निचले बिंदु पर"]], 2, "Free charges rearrange until the internal field vanishes, leaving excess charge on the outer surface.", "मुक्त आवेश तब तक पुनर्व्यवस्थित होते हैं जब तक आंतरिक क्षेत्र शून्य न हो जाए; अतिरिक्त आवेश बाहरी सतह पर रहता है।"),
  q("Fact", "The electric field immediately outside a charged conductor is directed:", "आवेशित चालक के ठीक बाहर विद्युत क्षेत्र की दिशा होती है:", [["Tangential to the surface", "सतह के स्पर्शीय"], ["Normal to the surface", "सतह के अभिलंब"], ["Always horizontal", "सदैव क्षैतिज"], ["Always vertically downward", "सदैव ऊर्ध्वाधर नीचे"]], 1, "A tangential component would move free charges, so the electrostatic field must be normal to the surface.", "स्पर्शीय घटक मुक्त आवेशों को चला देगा, इसलिए विद्युत स्थैतिक क्षेत्र सतह के अभिलंब होना चाहिए।"),
  q("Theory", "The electric potential throughout a conductor in electrostatic equilibrium is:", "विद्युत स्थैतिक संतुलन में चालक के पूरे भाग का विद्युत विभव होता है:", [["Zero in every case", "हर स्थिति में शून्य"], ["Constant", "नियत"], ["Maximum only at the centre", "केवल केंद्र पर अधिकतम"], ["Inversely proportional to volume", "आयतन के व्युत्क्रमानुपाती"]], 1, "Since E = -dV/dr and the internal electric field is zero, the conductor is an equipotential body.", "चूँकि E = -dV/dr और आंतरिक विद्युत क्षेत्र शून्य है, इसलिए चालक एक समविभव पिंड है।"),
  q("Application", "The protection of a sensitive instrument inside a closed conducting enclosure is based on:", "बंद चालक आवरण के भीतर संवेदनशील यंत्र की सुरक्षा किस सिद्धांत पर आधारित है?", [["Electrostatic shielding", "विद्युत स्थैतिक परिरक्षण"], ["Resonance", "अनुनाद"], ["Electromagnetic induction", "विद्युत चुंबकीय प्रेरण"], ["Photoelectric effect", "प्रकाश-विद्युत प्रभाव"]], 0, "A closed conductor shields its cavity from external static electric fields.", "बंद चालक अपने अंदर की गुहा को बाहरी स्थिर विद्युत क्षेत्रों से सुरक्षित रखता है।"),
  q("Theory", "An empty cavity inside a conductor is placed in electrostatic equilibrium with no charge inside the cavity. The field in the cavity is:", "विद्युत स्थैतिक संतुलन वाले चालक की खाली गुहा में कोई आवेश नहीं है। गुहा के भीतर क्षेत्र होगा:", [["Zero", "शून्य"], ["Uniform and non-zero", "एकसमान और अशून्य"], ["Infinite", "अनंत"], ["Dependent on cavity volume only", "केवल गुहा के आयतन पर निर्भर"]], 0, "Electrostatic shielding makes the field zero in an empty closed cavity of a conductor.", "विद्युत स्थैतिक परिरक्षण के कारण चालक की खाली बंद गुहा में क्षेत्र शून्य होता है।"),
  q("Theory", "When a neutral conductor is placed in an external electric field, its net charge:", "उदासीन चालक को बाहरी विद्युत क्षेत्र में रखने पर उसका कुल आवेश:", [["Becomes positive", "धनात्मक हो जाता है"], ["Becomes negative", "ऋणात्मक हो जाता है"], ["Remains zero although charges redistribute", "शून्य रहता है, यद्यपि आवेश पुनर्वितरित होते हैं"], ["Becomes infinite", "अनंत हो जाता है"]], 2, "The field induces surface-charge separation, but the conductor's total charge remains zero.", "क्षेत्र सतही आवेशों का पृथक्करण करता है, पर चालक का कुल आवेश शून्य ही रहता है।"),
  q("Fact", "For a fixed enclosed charge, changing the shape of a closed Gaussian surface changes the net flux by:", "नियत परिबद्ध आवेश के लिए बंद गाउसीय पृष्ठ का आकार बदलने पर कुल फ्लक्स में परिवर्तन होगा:", ["Zero", "q/ε₀", "2q/ε₀", "Depends on surface area"], 0, "Gauss's law makes net flux depend only on enclosed charge, not on the surface shape.", "गाउस नियम के अनुसार कुल फ्लक्स केवल परिबद्ध आवेश पर निर्भर करता है, पृष्ठ के आकार पर नहीं।"),
  q("Theory", "A point charge lies outside a closed surface. Its contribution to the net flux through that surface is:", "एक बिंदु आवेश बंद पृष्ठ के बाहर स्थित है। उस पृष्ठ से कुल फ्लक्स में उसका योगदान है:", [["Zero", "शून्य"], ["q/ε₀", "q/ε₀"], ["q/(2ε₀)", "q/(2ε₀)"], ["Infinite", "अनंत"]], 0, "Field lines entering and leaving due to an external charge contribute equal and opposite flux, giving zero net flux.", "बाहरी आवेश के कारण प्रवेश और निर्गमन करने वाली क्षेत्र रेखाओं के फ्लक्स बराबर और विपरीत होते हैं, इसलिए कुल फ्लक्स शून्य है।"),
  q("Fact", "Electric field lines of a dipole begin and end respectively on:", "विद्युत द्विध्रुव की क्षेत्र रेखाएँ क्रमशः कहाँ से आरंभ और समाप्त होती हैं?", [["Negative and positive charges", "ऋण और धन आवेश"], ["Positive and negative charges", "धन और ऋण आवेश"], ["Both at infinity", "दोनों अनंत पर"], ["The midpoint and infinity", "मध्य बिंदु और अनंत पर"]], 1, "Electric field lines originate on positive charge and terminate on negative charge.", "विद्युत क्षेत्र रेखाएँ धन आवेश से निकलती हैं और ऋण आवेश पर समाप्त होती हैं।"),
  q("Theory", "A dipole is in stable equilibrium in a uniform electric field when its dipole moment is:", "एकसमान विद्युत क्षेत्र में द्विध्रुव स्थायी संतुलन में होता है जब उसका द्विध्रुव आघूर्ण:", [["Parallel to the field", "क्षेत्र के समानांतर"], ["Antiparallel to the field", "क्षेत्र के विपरीत समानांतर"], ["Perpendicular to the field", "क्षेत्र के लंबवत"], ["Zero", "शून्य"]], 0, "Potential energy U = -pE cos θ is minimum at θ = 0, which is stable equilibrium.", "स्थितिज ऊर्जा U = -pE cos θ का मान θ = 0 पर न्यूनतम होता है, अतः यह स्थायी संतुलन है।"),
  q("Theory", "A dipole is in unstable equilibrium in a uniform electric field when its dipole moment is:", "एकसमान विद्युत क्षेत्र में द्विध्रुव अस्थायी संतुलन में होता है जब उसका द्विध्रुव आघूर्ण:", [["Parallel to the field", "क्षेत्र के समानांतर"], ["Antiparallel to the field", "क्षेत्र के विपरीत समानांतर"], ["At 60° to the field", "क्षेत्र से 60° पर"], ["At 90° to the field", "क्षेत्र से 90° पर"]], 1, "At θ = π, U = +pE is maximum, so the equilibrium is unstable.", "θ = π पर U = +pE अधिकतम होता है, इसलिए संतुलन अस्थायी है।"),
  q("Theory", "Electrostatic work between two fixed points is independent of:", "दो निश्चित बिंदुओं के बीच विद्युत स्थैतिक कार्य किससे स्वतंत्र होता है?", [["The path followed", "अपनाए गए पथ"], ["The end-point potentials", "अंतिम बिंदुओं के विभव"], ["The test charge", "परीक्षण आवेश"], ["The potential difference", "विभवांतर"]], 0, "Electrostatic force is conservative, so work depends only on the initial and final points.", "विद्युत स्थैतिक बल संरक्षी है, इसलिए कार्य केवल प्रारंभिक और अंतिम बिंदुओं पर निर्भर करता है।"),
  q("Fact", "The direction of the electric field is the direction in which electric potential:", "विद्युत क्षेत्र की दिशा वह दिशा है जिसमें विद्युत विभव:", [["Increases most rapidly", "सबसे तेजी से बढ़ता है"], ["Decreases most rapidly", "सबसे तेजी से घटता है"], ["Always remains zero", "सदैव शून्य रहता है"], ["Oscillates", "दोलन करता है"]], 1, "Because E = -∇V, the field points toward the steepest decrease of potential.", "E = -∇V के कारण क्षेत्र विभव के सबसे तीव्र ह्रास की दिशा में होता है।"),
  q("Theory", "Electric field lines cross an equipotential surface:", "विद्युत क्षेत्र रेखाएँ समविभव पृष्ठ को किस प्रकार काटती हैं?", [["Tangentially", "स्पर्शीय रूप से"], ["Normally", "अभिलंब रूप से"], ["At 45° always", "सदैव 45° पर"], ["They never meet it", "वे उसे कभी नहीं मिलतीं"]], 1, "No tangential field can exist on an equipotential surface, so field lines are normal to it.", "समविभव पृष्ठ पर स्पर्शीय क्षेत्र नहीं हो सकता, इसलिए क्षेत्र रेखाएँ उस पर अभिलंब होती हैं।"),
  q("Theory", "The electric potential due to several point charges is found using:", "अनेक बिंदु आवेशों के कारण विद्युत विभव किस सिद्धांत से ज्ञात किया जाता है?", [["Scalar superposition", "अदिश अध्यारोपण"], ["Vector multiplication", "सदिश गुणन"], ["Only Gauss's law", "केवल गाउस नियम"], ["Kirchhoff's current law", "किरचॉफ का धारा नियम"]], 0, "Potential is a scalar, so individual potentials are added algebraically.", "विभव एक अदिश राशि है, इसलिए अलग-अलग विभव बीजगणितीय रूप से जोड़े जाते हैं।"),
  q("Fact", "At a point where electric potential is zero, the electric field:", "जिस बिंदु पर विद्युत विभव शून्य है, वहाँ विद्युत क्षेत्र:", [["Must always be zero", "सदैव शून्य होना चाहिए"], ["May be non-zero", "अशून्य हो सकता है"], ["Must be infinite", "अनंत होना चाहिए"], ["Must reverse every second", "हर सेकंड दिशा बदलनी चाहिए"]], 1, "Zero potential is a scalar cancellation or reference value; its gradient may still be non-zero.", "शून्य विभव अदिश निरस्तीकरण या संदर्भ मान हो सकता है; उसका प्रवणता फिर भी अशून्य हो सकती है।"),
  q("Theory", "The capacitance of an isolated conductor primarily depends on:", "एक विलगित चालक की धारिता मुख्यतः किस पर निर्भर करती है?", [["Its charge only", "केवल उसके आवेश पर"], ["Its potential only", "केवल उसके विभव पर"], ["Geometry and surrounding medium", "ज्यामिति और आसपास के माध्यम पर"], ["Time of charging", "आवेशन के समय पर"]], 2, "Capacitance is determined by conductor geometry and the permittivity of its surroundings.", "धारिता चालक की ज्यामिति और उसके आसपास के माध्यम की विद्युतशीलता से निर्धारित होती है।"),
  q("Formula", "The capacitance of an isolated spherical conductor of radius R in vacuum is:", "निर्वात में त्रिज्या R वाले विलगित गोलाकार चालक की धारिता है:", ["4πε₀R", "ε₀R", "4πε₀/R", "R/(4πε₀)"], 0, "Using V = Q/(4πε₀R), capacitance C = Q/V = 4πε₀R.", "V = Q/(4πε₀R) से धारिता C = Q/V = 4πε₀R प्राप्त होती है।"),
  q("Application", "A charged capacitor remains connected to a battery while a dielectric of constant K is inserted. Its charge changes from Q to:", "एक आवेशित संधारित्र बैटरी से जुड़ा रहता है और K परावैद्युतांक का पदार्थ डाला जाता है। उसका आवेश Q से बदलकर होगा:", ["Q/K", "KQ", "Q", "K²Q"], 1, "The battery keeps V constant while C becomes KC, so Q = CV becomes KQ.", "बैटरी V को नियत रखती है और C का मान KC हो जाता है, इसलिए Q = CV से आवेश KQ हो जाता है।"),
  q("Application", "A capacitor remains connected to a battery while a dielectric of constant K is inserted. Its stored energy changes from U to:", "संधारित्र बैटरी से जुड़ा है और K परावैद्युतांक का पदार्थ डाला जाता है। उसकी संचित ऊर्जा U से बदलकर होगी:", ["U/K", "KU", "U", "K²U"], 1, "At constant V, U = ½CV². Since C becomes KC, energy becomes KU.", "नियत V पर U = ½CV² है। C का मान KC होने से ऊर्जा KU हो जाती है।"),
  q("Application", "An isolated charged capacitor receives a dielectric of constant K. Its stored energy changes from U to:", "एक विलगित आवेशित संधारित्र में K परावैद्युतांक का पदार्थ डाला जाता है। उसकी ऊर्जा U से बदलकर होगी:", ["KU", "U/K", "U", "K²U"], 1, "For an isolated capacitor Q is constant and U = Q²/(2C). Increasing C to KC reduces energy to U/K.", "विलगित संधारित्र में Q नियत और U = Q²/(2C) है। C से KC होने पर ऊर्जा U/K हो जाती है।"),
  q("Application", "A parallel-plate capacitor stays connected to a battery. If plate separation is doubled, its charge becomes:", "समांतर-पट्ट संधारित्र बैटरी से जुड़ा है। पट्टों की दूरी दोगुनी करने पर उसका आवेश होगा:", ["2Q", "Q/2", "Q", "4Q"], 1, "C = ε₀A/d halves when d doubles. With fixed V, Q = CV also halves.", "d दोगुना होने पर C = ε₀A/d आधा हो जाता है। V नियत होने से Q = CV भी आधा होता है।"),
  q("Fact", "Capacitors connected in parallel have the same:", "समांतर क्रम में जुड़े संधारित्रों में कौन-सी राशि समान होती है?", [["Charge", "आवेश"], ["Potential difference", "विभवांतर"], ["Capacitance", "धारिता"], ["Stored energy", "संचित ऊर्जा"]], 1, "Each parallel branch is connected across the same two nodes, so its potential difference is the same.", "प्रत्येक समांतर शाखा समान दो बिंदुओं के बीच जुड़ी होती है, इसलिए विभवांतर समान होता है।"),
  q("Fact", "Ideal capacitors connected in series carry equal magnitude of:", "श्रेणी क्रम में जुड़े आदर्श संधारित्रों पर किस राशि का परिमाण समान होता है?", [["Potential difference", "विभवांतर"], ["Charge", "आवेश"], ["Capacitance", "धारिता"], ["Energy density", "ऊर्जा घनत्व"]], 1, "The intermediate conductors remain neutral, giving equal and opposite charge magnitudes on every series capacitor.", "मध्यवर्ती चालक उदासीन रहते हैं, जिससे प्रत्येक श्रेणी संधारित्र पर समान परिमाण के विपरीत आवेश होते हैं।"),
  q("Theory", "A dielectric reduces the electric field inside a capacitor mainly because its molecules:", "परावैद्युत पदार्थ संधारित्र के भीतर विद्युत क्षेत्र को मुख्यतः इसलिए घटाता है क्योंकि उसके अणु:", [["Become radioactive", "रेडियोधर्मी हो जाते हैं"], ["Polarise and create an opposing field", "ध्रुवित होकर विपरीत क्षेत्र बनाते हैं"], ["Lose all electrons", "सभी इलेक्ट्रॉन खो देते हैं"], ["Stop moving permanently", "स्थायी रूप से गति रोक देते हैं"]], 1, "Polarisation produces bound surface charges whose field opposes the applied field.", "ध्रुवण से बंधित सतही आवेश उत्पन्न होते हैं जिनका क्षेत्र लगाए गए क्षेत्र का विरोध करता है।"),
  q("Fact", "Dielectric breakdown occurs when:", "परावैद्युत भंजन कब होता है?", [["The electric field exceeds the dielectric strength", "विद्युत क्षेत्र परावैद्युत सामर्थ्य से अधिक हो जाता है"], ["Capacitance becomes zero", "धारिता शून्य हो जाती है"], ["The plates become exactly parallel", "पट्ट पूर्णतः समांतर हो जाते हैं"], ["Potential is one volt", "विभव एक वोल्ट होता है"]], 0, "Beyond dielectric strength, the material ionises and begins conducting strongly.", "परावैद्युत सामर्थ्य से अधिक क्षेत्र पर पदार्थ आयनित होकर प्रबल चालन करने लगता है।"),
  q("Theory", "The electrostatic force is called conservative because:", "विद्युत स्थैतिक बल को संरक्षी क्यों कहा जाता है?", [["Its work over a closed path is zero", "बंद पथ पर उसका कार्य शून्य होता है"], ["It is always attractive", "यह सदैव आकर्षी होता है"], ["It acts only in conductors", "यह केवल चालकों में कार्य करता है"], ["It has no direction", "इसकी कोई दिशा नहीं होती"]], 0, "A conservative force does zero net work around any closed path.", "संरक्षी बल किसी भी बंद पथ पर शुद्ध कार्य शून्य करता है।"),
];

const set3Questions = [
  q("Formula", "Charges 2 μC and 3 μC are 0.30 m apart in vacuum. The force between them is:", "2 μC और 3 μC के आवेश निर्वात में 0.30 m दूर हैं। उनके बीच बल है:", ["0.2 N", "0.6 N", "1.8 N", "6 N"], 1, "F = kq₁q₂/r² = 9×10⁹×2×10⁻⁶×3×10⁻⁶/(0.30)² = 0.6 N.", "F = kq₁q₂/r² = 9×10⁹×2×10⁻⁶×3×10⁻⁶/(0.30)² = 0.6 N।"),
  q("Formula", "Charges 4 μC and 5 μC are separated by 0.20 m. Their Coulomb force in vacuum is:", "4 μC और 5 μC के आवेश 0.20 m दूर हैं। निर्वात में कूलॉम बल है:", ["0.45 N", "2.25 N", "4.5 N", "9 N"], 2, "F = 9×10⁹×4×10⁻⁶×5×10⁻⁶/(0.20)² = 4.5 N.", "F = 9×10⁹×4×10⁻⁶×5×10⁻⁶/(0.20)² = 4.5 N।"),
  q("Formula", "Two equal charges of 1 μC each are 0.10 m apart. The electrostatic force is:", "1 μC के दो समान आवेश 0.10 m दूर हैं। विद्युत स्थैतिक बल है:", ["0.09 N", "0.9 N", "9 N", "90 N"], 1, "F = 9×10⁹×(10⁻⁶)²/(0.10)² = 0.9 N.", "F = 9×10⁹×(10⁻⁶)²/(0.10)² = 0.9 N।"),
  q("Formula", "If the distance between two unchanged point charges becomes three times, the new force is:", "दो अपरिवर्तित बिंदु आवेशों की दूरी तीन गुनी होने पर नया बल होगा:", ["3F", "F/3", "F/6", "F/9"], 3, "Coulomb force varies as 1/r²; replacing r by 3r gives F/9.", "कूलॉम बल 1/r² के अनुसार बदलता है; r के स्थान पर 3r रखने से F/9 मिलता है।"),
  q("Formula", "Both point charges are doubled while their separation remains unchanged. The force becomes:", "दोनों बिंदु आवेश दोगुने किए जाते हैं और दूरी नियत रहती है। बल होगा:", ["2F", "4F", "F/2", "F/4"], 1, "Since F ∝ q₁q₂, doubling both charges multiplies force by 2×2 = 4.", "F ∝ q₁q₂ होने से दोनों आवेश दोगुने करने पर बल 2×2 = 4 गुना होता है।"),
  q("Formula", "The electric field 0.30 m from a 2 μC point charge in vacuum is:", "निर्वात में 2 μC बिंदु आवेश से 0.30 m दूरी पर विद्युत क्षेत्र है:", ["2×10⁴ N C⁻¹", "2×10⁵ N C⁻¹", "6×10⁵ N C⁻¹", "9×10⁵ N C⁻¹"], 1, "E = kq/r² = 9×10⁹×2×10⁻⁶/(0.30)² = 2×10⁵ N C⁻¹.", "E = kq/r² = 9×10⁹×2×10⁻⁶/(0.30)² = 2×10⁵ N C⁻¹।"),
  q("Formula", "The electric field 0.50 m from a 5 μC charge is:", "5 μC आवेश से 0.50 m दूरी पर विद्युत क्षेत्र है:", ["1.8×10⁴ N C⁻¹", "9×10⁴ N C⁻¹", "1.8×10⁵ N C⁻¹", "4.5×10⁵ N C⁻¹"], 2, "E = 9×10⁹×5×10⁻⁶/(0.50)² = 1.8×10⁵ N C⁻¹.", "E = 9×10⁹×5×10⁻⁶/(0.50)² = 1.8×10⁵ N C⁻¹।"),
  q("Application", "A charge of 3 μC is placed in an electric field of 2×10⁴ N C⁻¹. The force is:", "3 μC आवेश को 2×10⁴ N C⁻¹ के क्षेत्र में रखा गया है। बल है:", ["0.006 N", "0.06 N", "0.6 N", "6 N"], 1, "F = qE = 3×10⁻⁶×2×10⁴ = 0.06 N.", "F = qE = 3×10⁻⁶×2×10⁴ = 0.06 N।"),
  q("Formula", "At what distance from a 4 μC charge is the electric field 9×10⁴ N C⁻¹?", "4 μC आवेश से किस दूरी पर विद्युत क्षेत्र 9×10⁴ N C⁻¹ होगा?", ["0.20 m", "0.40 m", "0.63 m", "1.0 m"], 2, "r = √(kq/E) = √(9×10⁹×4×10⁻⁶/9×10⁴) ≈ 0.63 m.", "r = √(kq/E) = √(9×10⁹×4×10⁻⁶/9×10⁴) ≈ 0.63 m।"),
  q("Formula", "A uniform field of 200 N C⁻¹ is normal to an area of 0.50 m². The electric flux is:", "200 N C⁻¹ का एकसमान क्षेत्र 0.50 m² क्षेत्रफल के अभिलंब है। विद्युत फ्लक्स है:", ["50 N m² C⁻¹", "100 N m² C⁻¹", "200 N m² C⁻¹", "400 N m² C⁻¹"], 1, "Φ = EA cos 0° = 200×0.50 = 100 N m² C⁻¹.", "Φ = EA cos 0° = 200×0.50 = 100 N m² C⁻¹।"),
  q("Formula", "A closed surface encloses charge 8.85×10⁻¹² C. Taking ε₀ = 8.85×10⁻¹² C² N⁻¹ m⁻², its flux is:", "एक बंद पृष्ठ 8.85×10⁻¹² C आवेश घेरता है। ε₀ = 8.85×10⁻¹² C² N⁻¹ m⁻² लेने पर फ्लक्स है:", ["0", "1 N m² C⁻¹", "8.85 N m² C⁻¹", "9×10⁹ N m² C⁻¹"], 1, "By Gauss's law, Φ = q/ε₀ = 1 N m² C⁻¹.", "गाउस नियम से Φ = q/ε₀ = 1 N m² C⁻¹।"),
  q("Formula", "The potential 0.20 m from a 2 μC point charge is:", "2 μC बिंदु आवेश से 0.20 m दूरी पर विभव है:", ["9×10³ V", "9×10⁴ V", "1.8×10⁵ V", "4.5×10⁵ V"], 1, "V = kq/r = 9×10⁹×2×10⁻⁶/0.20 = 9×10⁴ V.", "V = kq/r = 9×10⁹×2×10⁻⁶/0.20 = 9×10⁴ V।"),
  q("Formula", "The potential 0.50 m from a 5 μC point charge is:", "5 μC बिंदु आवेश से 0.50 m दूरी पर विभव है:", ["4.5×10⁴ V", "9×10⁴ V", "1.8×10⁵ V", "9×10⁵ V"], 1, "V = 9×10⁹×5×10⁻⁶/0.50 = 9×10⁴ V.", "V = 9×10⁹×5×10⁻⁶/0.50 = 9×10⁴ V।"),
  q("Application", "The potential difference across a 2 μC charge changes by 50 V. The magnitude of work is:", "2 μC आवेश के लिए विभवांतर 50 V बदलता है। कार्य का परिमाण है:", ["1×10⁻⁵ J", "1×10⁻⁴ J", "1×10⁻³ J", "0.1 J"], 1, "W = qΔV = 2×10⁻⁶×50 = 1×10⁻⁴ J.", "W = qΔV = 2×10⁻⁶×50 = 1×10⁻⁴ J।"),
  q("Formula", "The potential energy of charges 2 μC and 3 μC separated by 0.30 m is:", "0.30 m दूरी पर स्थित 2 μC और 3 μC आवेशों की स्थितिज ऊर्जा है:", ["0.018 J", "0.18 J", "1.8 J", "18 J"], 1, "U = kq₁q₂/r = 9×10⁹×2×10⁻⁶×3×10⁻⁶/0.30 = 0.18 J.", "U = kq₁q₂/r = 9×10⁹×2×10⁻⁶×3×10⁻⁶/0.30 = 0.18 J।"),
  q("Formula", "Charges ±2 μC are separated by 4 mm. Their dipole moment is:", "±2 μC आवेशों के बीच दूरी 4 mm है। द्विध्रुव आघूर्ण है:", ["2×10⁻⁹ C m", "4×10⁻⁹ C m", "8×10⁻⁹ C m", "8×10⁻⁶ C m"], 2, "p = qd = 2×10⁻⁶×4×10⁻³ = 8×10⁻⁹ C m.", "p = qd = 2×10⁻⁶×4×10⁻³ = 8×10⁻⁹ C m।"),
  q("Formula", "A dipole p = 3×10⁻⁸ C m is at 30° in a field 2×10⁵ N C⁻¹. Its torque is:", "p = 3×10⁻⁸ C m का द्विध्रुव 2×10⁵ N C⁻¹ क्षेत्र में 30° पर है। बल आघूर्ण है:", ["3×10⁻⁴ N m", "3×10⁻³ N m", "6×10⁻³ N m", "1.2×10⁻² N m"], 1, "τ = pE sin 30° = 3×10⁻⁸×2×10⁵×½ = 3×10⁻³ N m.", "τ = pE sin 30° = 3×10⁻⁸×2×10⁵×½ = 3×10⁻³ N m।"),
  q("Formula", "The work required to rotate a dipole from θ = 0 to θ = π in a uniform field is:", "एकसमान क्षेत्र में द्विध्रुव को θ = 0 से θ = π तक घुमाने के लिए आवश्यक कार्य है:", ["0", "pE", "2pE", "4pE"], 2, "ΔU = Uπ - U₀ = (+pE) - (-pE) = 2pE.", "ΔU = Uπ - U₀ = (+pE) - (-pE) = 2pE।"),
  q("Formula", "A vacuum parallel-plate capacitor has A = 0.020 m² and d = 1.0 mm. Its capacitance is approximately:", "निर्वात समांतर-पट्ट संधारित्र में A = 0.020 m² और d = 1.0 mm है। इसकी धारिता लगभग है:", ["17.7 pF", "88.5 pF", "177 pF", "885 pF"], 2, "C = ε₀A/d = 8.85×10⁻¹²×0.020/10⁻³ = 177 pF.", "C = ε₀A/d = 8.85×10⁻¹²×0.020/10⁻³ = 177 pF।"),
  q("Formula", "A 4 μF capacitor is charged to 12 V. The charge on it is:", "4 μF संधारित्र को 12 V तक आवेशित किया गया है। उस पर आवेश है:", ["3 μC", "16 μC", "48 μC", "96 μC"], 2, "Q = CV = 4 μF×12 V = 48 μC.", "Q = CV = 4 μF×12 V = 48 μC।"),
  q("Formula", "Energy stored in a 5 μF capacitor at 10 V is:", "10 V पर 5 μF संधारित्र में संचित ऊर्जा है:", ["25 μJ", "100 μJ", "250 μJ", "500 μJ"], 2, "U = ½CV² = ½×5×10⁻⁶×100 = 250 μJ.", "U = ½CV² = ½×5×10⁻⁶×100 = 250 μJ।"),
  q("Formula", "Two 3 μF capacitors connected in series have equivalent capacitance:", "दो 3 μF संधारित्र श्रेणी क्रम में जुड़े हैं। तुल्य धारिता है:", ["1.5 μF", "3 μF", "6 μF", "9 μF"], 0, "For two equal series capacitors, Cₑq = C/2 = 1.5 μF.", "दो समान श्रेणी संधारित्रों के लिए Cₑq = C/2 = 1.5 μF।"),
  q("Formula", "Capacitors 2 μF and 3 μF connected in parallel have equivalent capacitance:", "2 μF और 3 μF संधारित्र समांतर क्रम में जुड़े हैं। तुल्य धारिता है:", ["1.2 μF", "2.5 μF", "5 μF", "6 μF"], 2, "Parallel capacitances add: Cₑq = 2 + 3 = 5 μF.", "समांतर धारिताएँ जुड़ती हैं: Cₑq = 2 + 3 = 5 μF।"),
  q("Formula", "Capacitors 6 μF and 3 μF connected in series have equivalent capacitance:", "6 μF और 3 μF संधारित्र श्रेणी क्रम में जुड़े हैं। तुल्य धारिता है:", ["1 μF", "2 μF", "3 μF", "9 μF"], 1, "Cₑq = C₁C₂/(C₁+C₂) = 18/9 = 2 μF.", "Cₑq = C₁C₂/(C₁+C₂) = 18/9 = 2 μF।"),
  q("Formula", "Capacitors 2 μF, 3 μF and 6 μF are in series. Their equivalent capacitance is:", "2 μF, 3 μF और 6 μF संधारित्र श्रेणी क्रम में हैं। तुल्य धारिता है:", ["1 μF", "2 μF", "3 μF", "11 μF"], 0, "1/Cₑq = 1/2 + 1/3 + 1/6 = 1, so Cₑq = 1 μF.", "1/Cₑq = 1/2 + 1/3 + 1/6 = 1, इसलिए Cₑq = 1 μF।"),
  q("Formula", "A capacitor has Q = 20 μC and C = 4 μF. Its stored energy is:", "एक संधारित्र में Q = 20 μC और C = 4 μF है। संचित ऊर्जा है:", ["25 μJ", "50 μJ", "100 μJ", "200 μJ"], 1, "U = Q²/(2C) = (20×10⁻⁶)²/(8×10⁻⁶) = 50 μJ.", "U = Q²/(2C) = (20×10⁻⁶)²/(8×10⁻⁶) = 50 μJ।"),
  q("Application", "A capacitor remains connected to a battery while its plate separation is doubled. Its stored energy becomes:", "संधारित्र बैटरी से जुड़ा है और पट्टों की दूरी दोगुनी की जाती है। उसकी संचित ऊर्जा होगी:", ["2U", "U", "U/2", "U/4"], 2, "At fixed V, U = ½CV² and C ∝ 1/d, so doubling d makes U/2.", "नियत V पर U = ½CV² और C ∝ 1/d है, इसलिए d दोगुना करने पर ऊर्जा U/2 होती है।"),
  q("Application", "An isolated charged parallel-plate capacitor has its plate separation doubled. Its stored energy becomes:", "विलगित आवेशित समांतर-पट्ट संधारित्र के पट्टों की दूरी दोगुनी की जाती है। उसकी ऊर्जा होगी:", ["U/2", "U", "2U", "4U"], 2, "For fixed Q, U = Q²/(2C). Since C halves, energy doubles to 2U.", "नियत Q पर U = Q²/(2C) है। C आधा होने से ऊर्जा 2U हो जाती है।"),
  q("Formula", "A dielectric of constant 4 fully fills a capacitor of capacitance C. The new capacitance is:", "परावैद्युतांक 4 का पदार्थ C धारिता वाले संधारित्र को पूर्णतः भरता है। नई धारिता है:", ["C/4", "C", "2C", "4C"], 3, "For full dielectric filling, C' = KC = 4C.", "पूर्ण परावैद्युत भराव के लिए C' = KC = 4C।"),
  q("Formula", "The potential of a short dipole at a distant point (r, θ) is proportional to:", "लघु द्विध्रुव से दूर बिंदु (r, θ) पर विभव किसके समानुपाती है?", ["p cos θ/r²", "p sin θ/r²", "p cos θ/r", "p/r³"], 0, "The dipole potential is V = p cos θ/(4πε₀r²).", "द्विध्रुव का विभव V = p cos θ/(4πε₀r²) होता है।"),
];

const set4Questions = [
  q("Dimension", "The dimensional formula of electric charge is:", "विद्युत आवेश का विमीय सूत्र है:", ["[IT]", "[I/T]", "[MLT⁻²]", "[ML²T⁻³I⁻¹]"], 0, "Charge Q = current×time, so [Q] = [IT].", "आवेश Q = धारा×समय, इसलिए [Q] = [IT]।"),
  q("Dimension", "The dimensional formula of electric field is:", "विद्युत क्षेत्र का विमीय सूत्र है:", ["[MLT⁻³I⁻¹]", "[ML²T⁻³I⁻¹]", "[M⁻¹L⁻³T⁴I²]", "[IT]"], 0, "E = F/Q, hence [E] = [MLT⁻²]/[IT] = [MLT⁻³I⁻¹].", "E = F/Q, अतः [E] = [MLT⁻²]/[IT] = [MLT⁻³I⁻¹]।"),
  q("Dimension", "The dimensional formula of electric potential is:", "विद्युत विभव का विमीय सूत्र है:", ["[MLT⁻³I⁻¹]", "[ML²T⁻³I⁻¹]", "[M⁻¹L⁻²T⁴I²]", "[ML²T⁻²]"], 1, "Potential is work per charge, so [V] = [ML²T⁻²]/[IT] = [ML²T⁻³I⁻¹].", "विभव प्रति आवेश कार्य है, इसलिए [V] = [ML²T⁻²]/[IT] = [ML²T⁻³I⁻¹]।"),
  q("Dimension", "The dimensional formula of capacitance is:", "धारिता का विमीय सूत्र है:", ["[M⁻¹L⁻²T⁴I²]", "[ML²T⁻⁴I⁻²]", "[M⁻¹L⁻³T⁴I²]", "[IT]"], 0, "C = Q/V gives [C] = [IT]/[ML²T⁻³I⁻¹] = [M⁻¹L⁻²T⁴I²].", "C = Q/V से [C] = [IT]/[ML²T⁻³I⁻¹] = [M⁻¹L⁻²T⁴I²]।"),
  q("Dimension", "The dimensional formula of vacuum permittivity ε₀ is:", "निर्वात विद्युतशीलता ε₀ का विमीय सूत्र है:", ["[M⁻¹L⁻³T⁴I²]", "[ML³T⁻⁴I⁻²]", "[M⁻¹L⁻²T⁴I²]", "[MLT⁻³I⁻¹]"], 0, "From Coulomb's law, ε₀ has dimensions [Q²/(Fr²)] = [M⁻¹L⁻³T⁴I²].", "कूलॉम नियम से ε₀ की विमा [Q²/(Fr²)] = [M⁻¹L⁻³T⁴I²] है।"),
  q("Unit", "The SI unit of electric flux is:", "विद्युत फ्लक्स का SI मात्रक है:", ["N m² C⁻¹", "N C⁻²", "V m⁻²", "C m⁻²"], 0, "Flux Φ = E·A, so its unit is (N C⁻¹)m² = N m² C⁻¹.", "फ्लक्स Φ = E·A, इसलिए मात्रक (N C⁻¹)m² = N m² C⁻¹ है।"),
  q("Unit", "The SI unit of electric dipole moment is:", "विद्युत द्विध्रुव आघूर्ण का SI मात्रक है:", ["C m", "C m⁻¹", "N C⁻¹", "J C⁻¹"], 0, "Dipole moment p = charge×separation, giving unit C m.", "द्विध्रुव आघूर्ण p = आवेश×दूरी, इसलिए मात्रक C m है।"),
  q("Unit", "The SI unit of surface charge density is:", "पृष्ठ आवेश घनत्व का SI मात्रक है:", ["C m⁻¹", "C m⁻²", "C m⁻³", "N C⁻¹"], 1, "Surface charge density σ = Q/A, so its unit is C m⁻².", "पृष्ठ आवेश घनत्व σ = Q/A, इसलिए मात्रक C m⁻² है।"),
  q("Unit", "The SI unit of electrostatic energy density is:", "विद्युत स्थैतिक ऊर्जा घनत्व का SI मात्रक है:", ["J m⁻¹", "J m⁻²", "J m⁻³", "J C⁻¹"], 2, "Energy density is energy per volume, so its SI unit is J m⁻³.", "ऊर्जा घनत्व प्रति आयतन ऊर्जा है, इसलिए SI मात्रक J m⁻³ है।"),
  q("Unit", "The SI unit of Coulomb constant k is:", "कूलॉम नियतांक k का SI मात्रक है:", ["N m² C⁻²", "N m C⁻¹", "C² N⁻¹ m⁻²", "J C⁻¹"], 0, "From F = kq₁q₂/r², k has unit N m² C⁻².", "F = kq₁q₂/r² से k का मात्रक N m² C⁻² है।"),
  q("Dimension", "Relative permittivity (dielectric constant) is:", "सापेक्ष विद्युतशीलता (परावैद्युतांक) है:", [["Dimensionless", "विमाहीन"], ["Measured in farad", "फैराड में मापी जाती है"], ["Measured in volt", "वोल्ट में मापी जाती है"], ["Measured in coulomb", "कूलॉम में मापी जाती है"]], 0, "Relative permittivity is the ratio ε/ε₀ and therefore has no dimensions.", "सापेक्ष विद्युतशीलता ε/ε₀ का अनुपात है, इसलिए यह विमाहीन है।"),
  q("Unit", "The SI unit of potential coefficient is:", "विभव गुणांक का SI मात्रक है:", ["V C⁻¹", "V C", "C V⁻¹", "N C⁻¹"], 0, "A potential coefficient relates potential to charge, so its unit is V/C.", "विभव गुणांक विभव को आवेश से संबंधित करता है, इसलिए इसका मात्रक V/C है।"),
  q("Unit", "The reciprocal of capacitance is called elastance and has unit:", "धारिता के व्युत्क्रम को इलास्टेंस कहते हैं और इसका मात्रक है:", ["F", "F⁻¹", "V", "C"], 1, "Elastance S = 1/C, so its unit is inverse farad, F⁻¹.", "इलास्टेंस S = 1/C, इसलिए इसका मात्रक प्रतिलोम फैराड F⁻¹ है।"),
  q("Unit", "Which of the following is NOT a unit of energy?", "निम्न में से कौन ऊर्जा का मात्रक नहीं है?", ["J", "C V", "N m", "F"], 3, "Farad is the unit of capacitance; J, C V and N m are energy units.", "फैराड धारिता का मात्रक है; J, C V और N m ऊर्जा के मात्रक हैं।"),
  q("Unit", "Electric field can also be expressed in the equivalent SI unit:", "विद्युत क्षेत्र को किस समतुल्य SI मात्रक में भी व्यक्त किया जा सकता है?", ["V m⁻¹", "V m", "C m⁻¹", "J m⁻¹"], 0, "Since E = -dV/dr, N C⁻¹ is equivalent to V m⁻¹.", "E = -dV/dr होने से N C⁻¹ का समतुल्य मात्रक V m⁻¹ है।"),
  q("Fact", "One microfarad equals:", "एक माइक्रोफैराड बराबर है:", ["10⁻³ F", "10⁻⁶ F", "10⁻⁹ F", "10⁻¹² F"], 1, "The SI prefix micro (μ) denotes 10⁻⁶.", "SI उपसर्ग माइक्रो (μ) का अर्थ 10⁻⁶ है।"),
  q("Fact", "The magnitude of the elementary charge is approximately:", "मूल आवेश का परिमाण लगभग है:", ["1.6×10⁻¹⁹ C", "9.1×10⁻³¹ C", "6.67×10⁻¹¹ C", "8.85×10⁻¹² C"], 0, "The elementary charge magnitude is e = 1.602×10⁻¹⁹ C.", "मूल आवेश का परिमाण e = 1.602×10⁻¹⁹ C है।"),
  q("Fact", "The approximate value of vacuum permittivity ε₀ is:", "निर्वात विद्युतशीलता ε₀ का लगभग मान है:", ["8.85×10⁻¹² C² N⁻¹ m⁻²", "9×10⁹ C² N⁻¹ m⁻²", "1.6×10⁻¹⁹ C", "6.02×10²³ F m⁻¹"], 0, "In SI units ε₀ ≈ 8.85×10⁻¹² C² N⁻¹ m⁻².", "SI मात्रकों में ε₀ ≈ 8.85×10⁻¹² C² N⁻¹ m⁻²।"),
  q("Fact", "The approximate value of 1/(4πε₀) in vacuum is:", "निर्वात में 1/(4πε₀) का लगभग मान है:", ["9×10⁹ N m² C⁻²", "8.85×10⁻¹² N m² C⁻²", "3×10⁸ N m² C⁻²", "1.6×10⁻¹⁹ N m² C⁻²"], 0, "The Coulomb constant k = 1/(4πε₀) ≈ 9×10⁹ N m² C⁻².", "कूलॉम नियतांक k = 1/(4πε₀) ≈ 9×10⁹ N m² C⁻²।"),
  q("Fact", "One electron-volt is equal to:", "एक इलेक्ट्रॉन-वोल्ट बराबर है:", ["1.6×10⁻¹⁹ J", "1 J", "9×10⁹ J", "8.85×10⁻¹² J"], 0, "1 eV is the energy gained by charge e across 1 V, equal to 1.602×10⁻¹⁹ J.", "1 eV वह ऊर्जा है जो आवेश e को 1 V विभवांतर से मिलती है, अर्थात 1.602×10⁻¹⁹ J।"),
  q("Fact", "A greater density of electric field lines in a region represents:", "किसी क्षेत्र में विद्युत क्षेत्र रेखाओं का अधिक घनत्व दर्शाता है:", [["A stronger electric field", "अधिक प्रबल विद्युत क्षेत्र"], ["A weaker electric field", "कमजोर विद्युत क्षेत्र"], ["Zero potential only", "केवल शून्य विभव"], ["No charge anywhere", "कहीं कोई आवेश नहीं"]], 0, "Field-line density is drawn proportional to the magnitude of the electric field.", "क्षेत्र रेखाओं का घनत्व विद्युत क्षेत्र के परिमाण के समानुपाती दर्शाया जाता है।"),
  q("Fact", "Electric flux is a:", "विद्युत फ्लक्स एक है:", [["Scalar quantity", "अदिश राशि"], ["Vector quantity", "सदिश राशि"], ["Dimensionless vector", "विमाहीन सदिश"], ["Tensor only", "केवल टेन्सर"]], 0, "Flux is the scalar surface integral ∫E·dA, so it is a scalar.", "फ्लक्स अदिश पृष्ठ समाकल ∫E·dA है, इसलिए यह अदिश राशि है।"),
  q("Fact", "The electric dipole moment vector points from:", "विद्युत द्विध्रुव आघूर्ण सदिश की दिशा होती है:", [["Positive to negative charge", "धन से ऋण आवेश की ओर"], ["Negative to positive charge", "ऋण से धन आवेश की ओर"], ["The midpoint to infinity", "मध्य बिंदु से अनंत की ओर"], ["Higher mass to lower mass", "अधिक द्रव्यमान से कम द्रव्यमान की ओर"]], 1, "By convention, dipole moment points from negative charge to positive charge.", "परंपरा के अनुसार द्विध्रुव आघूर्ण ऋण आवेश से धन आवेश की ओर होता है।"),
  q("Fact", "At any point, the tangent to an electric field line gives:", "किसी बिंदु पर विद्युत क्षेत्र रेखा की स्पर्शरेखा बताती है:", [["Direction of electric field", "विद्युत क्षेत्र की दिशा"], ["Direction of current always", "सदैव धारा की दिशा"], ["Value of potential only", "केवल विभव का मान"], ["Mass of test charge", "परीक्षण आवेश का द्रव्यमान"]], 0, "The tangent to a field line is defined to be along the local electric field.", "क्षेत्र रेखा की स्पर्शरेखा स्थानीय विद्युत क्षेत्र की दिशा में परिभाषित होती है।"),
  q("Fact", "Electrostatic field lines do not form closed loops because the field is:", "विद्युत स्थैतिक क्षेत्र रेखाएँ बंद लूप नहीं बनातीं क्योंकि क्षेत्र है:", [["Conservative", "संरक्षी"], ["Always uniform", "सदैव एकसमान"], ["Always radial", "सदैव त्रिज्यीय"], ["Time varying", "समय परिवर्ती"]], 0, "A closed field-line loop would imply non-zero work around a closed path, contradicting conservative electrostatics.", "बंद क्षेत्र रेखा लूप बंद पथ पर अशून्य कार्य दर्शाएगा, जो संरक्षी विद्युत स्थैतिक क्षेत्र के विपरीत है।"),
  q("Fact", "Inside a charged conducting spherical shell, electric potential is:", "आवेशित चालक गोलाकार खोल के भीतर विद्युत विभव है:", [["Constant and equal to the surface potential", "नियत और सतही विभव के बराबर"], ["Zero in every case", "हर स्थिति में शून्य"], ["Proportional to distance from centre", "केंद्र से दूरी के समानुपाती"], ["Infinite at the centre", "केंद्र पर अनंत"]], 0, "The internal field is zero, so potential has no spatial change and equals the surface value.", "आंतरिक क्षेत्र शून्य है, इसलिए विभव स्थान के साथ नहीं बदलता और सतही मान के बराबर रहता है।"),
  q("Formula", "The electric field just outside a conductor with surface charge density σ is:", "पृष्ठ आवेश घनत्व σ वाले चालक के ठीक बाहर विद्युत क्षेत्र है:", ["σ/ε₀", "σ/(2ε₀)", "2σ/ε₀", "ε₀σ"], 0, "Using a Gaussian pillbox with zero internal field gives E = σ/ε₀ just outside a conductor.", "गाउसीय पिलबॉक्स और शून्य आंतरिक क्षेत्र से चालक के बाहर E = σ/ε₀ मिलता है।"),
  q("Formula", "Electrostatic pressure on a conductor carrying surface charge density σ is:", "पृष्ठ आवेश घनत्व σ वाले चालक पर विद्युत स्थैतिक दाब है:", ["σ²/(2ε₀)", "σ/ε₀", "2σ²/ε₀", "ε₀σ²"], 0, "The outward electrostatic pressure is P = ½ε₀E² = σ²/(2ε₀).", "बाहर की ओर विद्युत स्थैतिक दाब P = ½ε₀E² = σ²/(2ε₀) होता है।"),
  q("Fact", "The capacitance of an isolated sphere is directly proportional to its:", "विलगित गोले की धारिता किसके समानुपाती होती है?", [["Radius", "त्रिज्या"], ["Surface charge only", "केवल सतही आवेश"], ["Potential squared", "विभव के वर्ग"], ["Mass", "द्रव्यमान"]], 0, "For an isolated sphere C = 4πε₀R, hence C ∝ R.", "विलगित गोले के लिए C = 4πε₀R, अतः C ∝ R।"),
  q("Fact", "The electric charge carried by an electron is:", "इलेक्ट्रॉन द्वारा वहन किया गया विद्युत आवेश है:", ["+e", "-e", "0", "+2e"], 1, "An electron carries one negative elementary charge, -e.", "इलेक्ट्रॉन एक ऋणात्मक मूल आवेश -e वहन करता है।"),
];

const original = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
const withIds = (questions) => questions.map((question, index) => ({ id: index + 1, ...question }));
const tests = [
  {
    id: "set-01",
    number: 1,
    titleEn: "Electrostatics Test Set 01",
    titleHi: "स्थिर वैद्युतिकी टेस्ट सेट 01",
    focusEn: "Foundation Mix",
    focusHi: "आधारभूत मिश्रित प्रश्न",
    downloadPath: "/downloads/class-12-board-2027-electrostatics-test-set-01.pdf",
    questions: original.questions,
  },
  {
    id: "set-02",
    number: 2,
    titleEn: "Electrostatics Test Set 02",
    titleHi: "स्थिर वैद्युतिकी टेस्ट सेट 02",
    focusEn: "Theory and Concepts",
    focusHi: "सिद्धांत एवं अवधारणाएँ",
    downloadPath: "/downloads/class-12-board-2027-electrostatics-test-set-02.pdf",
    questions: withIds(set2Questions),
  },
  {
    id: "set-03",
    number: 3,
    titleEn: "Electrostatics Test Set 03",
    titleHi: "स्थिर वैद्युतिकी टेस्ट सेट 03",
    focusEn: "Formula and Applications",
    focusHi: "सूत्र एवं अनुप्रयोग",
    downloadPath: "/downloads/class-12-board-2027-electrostatics-test-set-03.pdf",
    questions: withIds(set3Questions),
  },
  {
    id: "set-04",
    number: 4,
    titleEn: "Electrostatics Test Set 04",
    titleHi: "स्थिर वैद्युतिकी टेस्ट सेट 04",
    focusEn: "Units, Dimensions and Facts",
    focusHi: "मात्रक, विमाएँ एवं तथ्य",
    downloadPath: "/downloads/class-12-board-2027-electrostatics-test-set-04.pdf",
    questions: withIds(set4Questions),
  },
];

for (const test of tests) {
  if (test.questions.length !== 30) throw new Error(`${test.id} must contain exactly 30 questions`);
  for (const question of test.questions) {
    if (question.options.length !== 4) throw new Error(`${test.id} question ${question.id} must have four options`);
    if (question.correctOption < 0 || question.correctOption > 3) throw new Error(`${test.id} question ${question.id} has invalid answer`);
  }
}

const normalizedQuestions = tests.flatMap((test) => test.questions.map((question) => question.questionEn.trim().toLowerCase()));
if (new Set(normalizedQuestions).size !== normalizedQuestions.length) {
  throw new Error("Duplicate English question detected across Electrostatics sets");
}

fs.writeFileSync(outputPath, `${JSON.stringify({ tests }, null, 2)}\n`, "utf8");
console.log(`Created ${outputPath}`);
console.log(`Validated ${tests.length} sets and ${normalizedQuestions.length} unique questions`);
